// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKMekdL3-zvcVmFeBb6Qy0OzavYRPgSKg',
    appId: '1:572522187415:web:149085065b20fde290b7d2',
    messagingSenderId: '572522187415',
    projectId: 'studentapplication-a9af1',
    authDomain: 'studentapplication-a9af1.firebaseapp.com',
    storageBucket: 'studentapplication-a9af1.appspot.com',
    measurementId: 'G-QX54CJ5PYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCG2flYmRkJB27NXfRC9M4sK2Jn7OI6zM',
    appId: '1:572522187415:android:a54cab1ca8dc055290b7d2',
    messagingSenderId: '572522187415',
    projectId: 'studentapplication-a9af1',
    storageBucket: 'studentapplication-a9af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsKB44R9nPikbHvsflTldSxHuuja8BIVg',
    appId: '1:572522187415:ios:6ef3b8986ecc631c90b7d2',
    messagingSenderId: '572522187415',
    projectId: 'studentapplication-a9af1',
    storageBucket: 'studentapplication-a9af1.appspot.com',
    iosBundleId: 'com.example.studentApplicationGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsKB44R9nPikbHvsflTldSxHuuja8BIVg',
    appId: '1:572522187415:ios:6ef3b8986ecc631c90b7d2',
    messagingSenderId: '572522187415',
    projectId: 'studentapplication-a9af1',
    storageBucket: 'studentapplication-a9af1.appspot.com',
    iosBundleId: 'com.example.studentApplicationGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKMekdL3-zvcVmFeBb6Qy0OzavYRPgSKg',
    appId: '1:572522187415:web:5c8ccd7a35fc767790b7d2',
    messagingSenderId: '572522187415',
    projectId: 'studentapplication-a9af1',
    authDomain: 'studentapplication-a9af1.firebaseapp.com',
    storageBucket: 'studentapplication-a9af1.appspot.com',
    measurementId: 'G-0RYX013WD2',
  );
}
